### ISSUE TITLE
Run ats-amazi demos locally on desktop/laptop

### ISSUE THREAD

**Issue by aashish24** [Kitware/resonanthpc#1]
https://github.com/amanzi/ats-demos

**Comment by banesullivan** [comment]
Working on making docker containers for ATS - ref https://github.com/amanzi/amanzi/issues/422

**Comment by banesullivan** [comment]
Some notes.

- There are now two docker images on DockerHub maintained by the Amanzi team from https://github.com/amanzi/amanzi/issues/422
  - [`metsi/amanzi`](https://hub.docker.com/r/metsi/amanzi)
  - [`metsi/ats`](https://hub.docker.com/r/metsi/ats)
- I started by running the [two amanzi tutorials](https://amanzi.github.io/amanzi/UserGuide/tutorial/index.html) in the `metsi/amanzi` docker image. The first one worked great, the second one not so great - details in https://github.com/amanzi/amanzi/issues/425
- Now I am working to run the [ats-demos](https://github.com/amanzi/ats-demos) and will report back

**Comment by banesullivan** [comment]
I have the ats-demos running via a docker container created in https://github.com/amanzi/ats-demos/pull/2
