### ISSUE TITLE
Create a web site for the project

### ISSUE THREAD

**Issue by aashish24** [Kitware/resonanthpc#15]
- Project goal
- Team members
- GitHub repository link, tools using/used
- Screenshorts and videos
- Link to Kitware, LANL, and LBNL, ATS, VTK, CMB, and ParaView

**Comment by banesullivan** [comment]
See https://kwgitlab.kitware.com/ux-design/design-tracker/-/issues/51

**Comment by aashish24** [comment]
Feel free to add/remove content items as appropriate. Once UI/UX team has a template, we could take a look at it together.
