### ISSUE TITLE
ATS Feature Set: Field Evaluators

### ISSUE THREAD

**Issue by banesullivan** [Kitware/resonanthpc#27]
Implement the following field evaluators in full within CMB/SMTK templates (see progress on `v0/fe` branch)

- [x] `capillary pressure, atmospheric gas over liquid`
    - [Source](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/wrm/pc_liquid_evaluator_reg.hh)
- [x] `compressible porosity`
    - [Source](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/porosity/compressible_porosity_evaluator.cc)
- [x] `effective_pressure`
    - [Source](https://github.com/amanzi/amanzi/blob/master/src/pks/eos/EffectivePressureEvaluator.cc)
- [x] EOS (there may be a few types)
    - Doc:
    - Source:
- [x] `independent variable` (function and constant)
    - [x] Implement to support multiple regions (for Rock Creek) (done in 9a209af3592b20487bd3edf01ff19a2733f9ee5d)
    - [Doc](https://amanzi.github.io/ats/input_spec/ATSNativeSpec_dev.html#independentvariableevaluator)
    - [Source](https://github.com/amanzi/amanzi/blob/master/src/state/independent_variable_field_evaluator.cc) and [this](https://github.com/amanzi/amanzi/blob/master/src/mesh_functions/CompositeVectorFunctionFactory.cc) and [this](https://github.com/amanzi/amanzi/blob/master/src/functions/MultiFunction.cc)
- [x] `molar fraction gas`
    - [Doc](https://amanzi.github.io/ats/input_spec/ATSNativeSpec_dev.html#liquid-ice-gas-water-content)
    - [Source](https://github.com/amanzi/ats/blob/master/src/constitutive_relations/eos/molar_fraction_gas_evaluator.cc)
- [x] `multiplicative evaluator` (5 and Rock Creek)
    - this evaluator links several other evaluators together
    - [Source](https://github.com/amanzi/ats/blob/master/src/constitutive_relations/generic_evaluators/MultiplicativeEvaluator.cc)
- [x] `overland pressure water content`
    - [Doc](https://amanzi.github.io/ats/input_spec/ATSNativeSpec_dev.html#overland-flow-pk) ???
    - [Source](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/water_content/overland_pressure_water_content_evaluator.cc)
- [x] `ponded depth` (bar option also?)
    - [Source](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/elevation/volumetric_ponded_depth_evaluator.cc) ???
- [x] `richards water content`
    - [Doc](https://amanzi.github.io/ats/input_spec/ATSNativeSpec_dev.html#richards-equation-water-content)
    - [Source](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/water_content/richards_water_content_evaluator.cc)
- [x] `viscosity`
    - [Source](https://github.com/amanzi/ats/blob/master/src/constitutive_relations/eos/viscosity_evaluator.cc)

-------

To do:

- [ ] go back and check that our options match what is listed in the source.
- [ ] take note of any mismatch between the source and the docs/demos
- [ ] open an issue outlining any issues in the right place

**Comment by ecoon** [comment]
Best bet is just a find.  All evaluators are registered into a factory in a file called (eval_name)_reg.hh

So if you want to find the "ponded depth" evaluator, do a:

    find $AMANZI_SRC_DIR -name *_reg.hh -print | xargs grep "ponded depth"

Note that you need to escape the * on a mac, so `\*_reg.hh`.  From there it should be obvious.  Those "reg" files are quite small, so you shouldn't see a lot of extraneous matches.  For instance, ponded depth gives three -- "icy ponded depth", "volumetric ponded depth", and "ponded depth".  Given the reg file, just remove the "_reg" to find the class you're looking for.

**Comment by banesullivan** [comment]
Thanks, @ecoon

It is still a bit unclear to me which of those three classes is actually used when specifying `<Parameter name="field evaluator type" type="string" value="ponded depth"/>` in the input deck.

Also, I do not see any of the arguments like `ponded depth bar` or `height key` used in those three classes - yet they are listed in the demos. Is there something I am missing? How can I tell what are all of the options for this (and any other field evaluator)?

**Comment by banesullivan** [comment]
Actually, I suppose `height_evaluator` is the one used because that's the only one registered to the factory with the same key `"ponded depth"`, but my question on where to find all the options remains.

`src/pks/flow/constitutive_relations/elevation/height_evaluator.cc` does not list any of those arguments list under the evaluator in the demo input decks

**Comment by banesullivan** [comment]
Or perhaps those arguments in the demos aren't valid/used and I should implement the arguments listed within `height_evaluator.cc`: `allow negative ponded depth`, `mass density key`, `pressure key`, `gravity key`, and `height model parameters` (ref [these lines](https://github.com/amanzi/ats/blob/master/src/pks/flow/constitutive_relations/elevation/height_evaluator.cc#L19-L33))
