### ISSUE TITLE
Initial CMB workflow files

### ISSUE THREAD

**Issue by johnkit** [Kitware/resonanthpc#3]
Develop initial CMB UI template files and python scripts for generating ATS input files. The results from this task should be sufficient to model the ATS demo01 problem (steady state Richards).

Main results are:
* CMB/xml template files to produce the simulation UI in modelbuilder
* python scripts to generate ATS input files

### CMB template files

*Preceding `*` means it is blocking us from moving on*

- [x] Mesh objects (generated)... *close to done on John's `refactor-mesh` branch - see #14*
  - #12 implements N domains/meshes
  - [x] generate mesh
  - [x] read mesh file
  - [x] *surface
  - Some others that I don't think are included in the demos: subgrid, column mesh, logical mesh (not documented)
- [x] Region objects (basic ones for demos)
  - [x] all
  - [x] box
  - [x] plane
  - [x] labeled set
  - [x] color function
  - [x] point
  - Some other regions that are not used in the demos: *logical, polygon, enumerated, boundary, box volume fractions, line segment*
- [x] Coordinator object ("cycle driver")
- [x] Visualization objects
- [x] Observation objects
  - how do we handle the `"variable"` parameter?: for now, user must manually input
- [x] Checkpoint
- [x] *PK objects - Richards PK only, subset of parameters
  - there are a ton of PKs... we can't get to all of them immediately, so only implement Richards and ones for other demos as needed
  - [x] the `04-...-v` demo needs a few other PKs beyond richards
  - [x] *time integrator objects
  - [x] *preconditioner objects (`boomer amg`)
  - [x] *PDE diffusion spec
  - [x] *what is the `water retention evaluator`???
  - [x] *Initial and boundary conditions in PKs - how are they different than State?
- [x] *State object
  - [x] *Field Evaluators
  - [x] *Initial Conditons

### Python export scripts

- [x] Mesh objects
- [x] Region objects
- [x] cycle driver (Coordinator object)
  - [x] create a mapping between our PK classes and their names in ATS for the `PK type` parameter on export
- [x] Visualization objects
- [x] Observation objects
- [x] Checkpoint
- [x] PK objects - Richards PK only
- [x] State object - constants only if possible

Other:

- [x] fix case issues in names of attributes

### Known limitations
* ~Only supports single mesh specified as 3D grid~
* Only supports Richards process kernel with limited parameters
* Only supports constant-valued data (no functions)

**Comment by johnkit** [comment]
Pushed `cmb-initial-dev` branch with some .sbt files to begin modeling ATS simulations. **Lots more needed** to reconstruct even the simplest example (demo 01).

**Comment by johnkit** [comment]
Some potentially helpful links:
* https://smtk.readthedocs.io/en/release/userguide/attribute/file-syntax.html describes the .sbt file syntax (though not  up to date for sure).
* https://gitlab.kitware.com/cmb/plugins/ace3p-extensions has a working set of .sbt files, starting with `simulation-workflows/ACE3P.sbt`
* https://gitlab.kitware.com/cmb/plugins/truchas-extensions has a working set of .sbt files starting with `simulation-workflows/Truchas.sbt`.

**Comment by banesullivan** [comment]
@johnkit - while looking at the baseline file for the Mesh/Domain/Region writer I saw something that I'm not sure about. You currently have three separate sections: `mesh`, `domain`, and `regions`. Is this intentional? I'm thinking there should only be 2 sections: `mesh` and `regions` while one of the mesh objects must have the name `domain`. That's what I am seeing in the demo files - no `domain` section, just one of the mesh objects is always called `domain`.

Should I change this?

**Comment by banesullivan** [comment]
I think we have finally reached a point where this task can be marked as complete! 🎉 

We have working CMB templates/export scripts for ATS Demos 01 and 04 under the `dev/cmb/simulation-workflows/ats/internal/tests/test_demos` directory. The baseline ATS XML input files included in that directory are what we can generate and they will run in ATS
