### ISSUE TITLE
Bio pictures are broken on website

### ISSUE THREAD

**Issue by banesullivan** [Kitware/resonanthpc#37]
All of the bio pictures are broken on https://kitware.github.io/resonanthpc/team/ and same with the pictures at the bottom of https://kitware.github.io/resonanthpc/

@jtomeck, any idea what went wrong here?

**Comment by jtomeck** [comment]
@banesullivan - Looks like it's related to #38. To fix this one, we'll want to add a prepend like so `{{ member.image | prepend: site.baseurl }}` to the team.html inside _includes.
