### ISSUE TITLE
Pick a suitable ESS use-case for the ResonantHPC 

### ISSUE THREAD

**Issue by aashish24** [Kitware/resonanthpc#4]

**Comment by banesullivan** [comment]
From looking at the example results, `04_integrated_hydro` might be a good choice as it has some 3D meshes we can use for visualization and an easy to follow workflow. Pluse the 2D hillslope is a classic hydro problem and worth having as a demo. Overall, the `ats-demos` geared more towards being a learning resource for the ATS package to highlight what it is capable of - while incredibly useful, these might not be as compelling as a full 3D reactive transport model.

I think we should reach out to the Amanzi team to see if we can get a real-world example with a mesh similar those shown on the project's home page: https://amanzi.github.io/gallery

It would be awesome to do a full reactive transport simulation or watershed model in addition to the simple cases like a 2D hillslope or column experiment.

![Screen Shot 2020-04-21 at 10 58 49 AM](https://user-images.githubusercontent.com/22067021/79881372-173bab00-83bf-11ea-8835-2ad43e92e557.png)

**Comment by aashish24** [comment]
For now 04_integrated_hydro is the choice for us to use as a use-case.
