### ISSUE TITLE
Evaluate ERDC Jupyter code by having it run locally on a workstation

### ISSUE THREAD

**Issue by aashish24** [Kitware/resonanthpc#5]

**Comment by banesullivan** [comment]
Done. I also spent some of my own time to experiment with the ERDC work with PyVista in https://github.com/pyvista/pyvista/pull/698. 

The C++ exporter isn't picking up or setting everything correctly and the changes in [this file](https://github.com/holoviz/panel/blob/b7eeedf1d7991c9171c10d9c88055d28af09ef74/panel/pane/vtk/synchronizable_serializer.py) (link might be outdated) will work perform the export correctly.  Eventually, that Python script will be backported to the C++ exporter.

**Comment by banesullivan** [comment]
Technically, I don't have a *working* version of this running locally - all the pieces are being glued together by panel though. We will need to way for the exporter to be updated in VTK before we can use the `vtkJSONRenderWindowExporter` class
