### ISSUE TITLE
SMTK template component reuse

### ISSUE THREAD

**Issue by johnkit** [Kitware/resonanthpc#8]
There are a number of specifications that get used in many places throughout ATS. Currently there is no easy way to step and repeat such components. We need to decide a strategy for reusing components. Current alternatives are:
* stick with brute force
* switch to pug templates (pug is nodejs based)
* switch to xslt, jinja or some other python templating method
* extend SMTK to support "item templates" - there is already a feature request, but no active work
* update the SMTK TemplateEditor application to support this (outside the core smtk library)

**Comment by johnkit** [comment]
Tradeoffs include
* Effort required in Phase I of ResonantHPC
* Effort required to support templates when scaled to the full ATS/Amanzi feature set
* Effort required for non-developers to support ATS templates in the future

**Comment by johnkit** [comment]
TemplateEditor is **NOT** a good option: To my chagrin, it only supports attribute views right now., generates monolithic output (although that might be easy to fix), and I suspect it doesn't support the full item feature set. It would take too much time and money to address these issues now. Maybe in Phase 2?

**Comment by johnkit** [comment]
@banesullivan  I meant to cc you on this earlier today. Mostly FYI.

One additional comment: I included XSLT as a python templating option: (i) I see that it is available in lxml (which *I think* CMB requires), and (ii) the syntax we need to insert content is pretty trival.

**Comment by banesullivan** [comment]
Hm, there is a lot to consider here...

We could also implement some classes via nifty inheritance from the Python `xml` standard library and start to create a Python-based SMTK schema. 

I am going to keep exploring these options, trying out a few things, and see what would work best for us and to make sure it is maintainable down the road with the Amanzi group in mind.

**Comment by johnkit** [comment]
Decided to go with XInclude preprocessing
* Use <xi:include> elements in source files
* python script to perform XInclude in a preprocessing step
First implemented in bane-cmb-dev branch
